export const STUDENT_COLUMNS = [
  { key: 'first_name', label: 'First Name' },
  { key: 'last_name', label: 'Last Name' },
  { key: 'reg_no', label: 'Register Number' },
  { key: 'roll_number', label: 'Roll Number' },
  { key: 'email_address', label: 'Email Address' },
  { key: 'alternate_email', label: 'Alternate Email' },
  { key: 'mobile_number', label: 'Mobile Number' },
  { key: 'whatsapp_number', label: 'WhatsApp Number' },
  { key: 'date_of_birth', label: 'Date of Birth' },
  { key: 'gender', label: 'Gender' },
  { key: 'blood_group', label: 'Blood Group' },
  { key: 'marital_status', label: 'Marital Status' },
  { key: 'aadhar_number', label: 'Aadhar Number' },
  { key: 'pan_number', label: 'PAN Number' },
  { key: 'passport_available', label: 'Passport Available' },
  { key: 'passport_number', label: 'Passport Number' },
  { key: 'nationality', label: 'Nationality' },
  { key: 'state', label: 'State' },
  { key: 'district', label: 'District' },
  { key: 'mother_tongue', label: 'Mother Tongue' },
  { key: 'religion', label: 'Religion' },
  { key: 'community', label: 'Community' },
  { key: 'caste', label: 'Caste' },
  
  // Academic
  { key: 'tenth_board', label: '10th Board' },
  { key: 'tenth_school_name', label: '10th School' },
  { key: 'tenth_percentage', label: '10th %' },
  { key: 'twelfth_school_board', label: '12th Board' },
  { key: 'twelfth_school_name', label: '12th School' },
  { key: 'twelfth_percentage', label: '12th %' },
  { key: 'diploma_studied', label: 'Diploma Studied' },
  { key: 'diploma_institute_name', label: 'Diploma Institute' },
  { key: 'diploma_stream', label: 'Diploma Stream' },
  { key: 'work_experience', label: 'Work Experience' },
  
  // College Performance
  { key: 'current_year', label: 'Current Year' },
  { key: 'current_semester', label: 'Current Semester' },
  { key: 'sem_1_cgpa', label: 'Sem 1 CGPA' },
  { key: 'sem_2_cgpa', label: 'Sem 2 CGPA' },
  { key: 'sem_3_cgpa', label: 'Sem 3 CGPA' },
  { key: 'sem_4_cgpa', label: 'Sem 4 CGPA' },
  { key: 'sem_5_cgpa', label: 'Sem 5 CGPA' },
  { key: 'sem_6_cgpa', label: 'Sem 6 CGPA' },
  { key: 'sem_7_cgpa', label: 'Sem 7 CGPA' },
  { key: 'sem_8_cgpa', label: 'Sem 8 CGPA' },
  { key: 'overall_cgpa', label: 'Overall CGPA' },
  { key: 'current_standing_arrear', label: 'Current Standing Arrear' },
  { key: 'current_backlogs', label: 'Current Backlogs' },
  { key: 'history_of_arrear', label: 'History of Arrear' },
  { key: 'history_of_arrears_count', label: 'Arrears Count' },
  
  // College Info
  { key: 'degree_branches', label: 'Department / Branch' },
  { key: 'regulations', label: 'Regulations' },
  { key: 'batches', label: 'Batch' },
  { key: 'section', label: 'Section' },
  { key: 'quota', label: 'Quota' },
  { key: 'medium', label: 'Medium' },
  { key: 'mode_of_education', label: 'Mode of Education' },
  { key: 'mode_of_admission', label: 'Mode of Admission' },
  { key: 'student_status', label: 'Student Status' },
  
  // Family & Communication
  { key: 'father_guardian_name', label: 'Father/Guardian Name' },
  { key: 'occupation_father_guardian', label: 'Father Occupation' },
  { key: 'father_mobile_number', label: 'Father Mobile' },
  { key: 'mother_name', label: 'Mother Name' },
  { key: 'mother_mobile_number', label: 'Mother Mobile' },
  { key: 'is_parent_farmer', label: 'Is Parent Farmer' },
  { key: 'communication_door_street', label: 'Door/Street' },
  { key: 'communication_area_village', label: 'Area/Village' },
  { key: 'communication_pincode', label: 'Pincode' },
  { key: 'is_hosteller', label: 'Hosteller/Day Scholar' },
  { key: 'hostel_name', label: 'Hostel Name' },
  
  // Placement
  { key: 'interested_in_placement', label: 'Interested in Placement' },
  { key: 'placement_opt_out_reason', label: 'Opt Out Reason' },
  { key: 'photo_url', label: 'Photo URL' },
  { key: 'resume_url', label: 'Resume URL' },
  { key: 'skills', label: 'IT Skills' },
  { key: 'programming_languages', label: 'Programming Languages' },
  { key: 'projects', label: 'Projects' },
  { key: 'internship_experience', label: 'Internships' },
  { key: 'certifications', label: 'Certifications' },
  { key: 'github_url', label: 'GitHub' },
  { key: 'linkedin_url', label: 'LinkedIn' },
  { key: 'leetcode_url', label: 'LeetCode' },
  { key: 'hackerrank_url', label: 'HackerRank' },
  { key: 'preferred_job_role', label: 'Preferred Role' },
  { key: 'preferred_location', label: 'Preferred Location' },
  
  // Other
  { key: 'extra_curricular', label: 'Extracurricular' },
  { key: 'geographic_classification', label: 'Geographic Area' },
  { key: 'is_physically_challenged', label: 'Physically Challenged' },
  { key: 'is_first_graduate', label: 'First Graduate' },
  { key: 'is_single_parent', label: 'Single Parent' },
  { key: 'is_ex_serviceman_child', label: 'Ex-Serviceman Child' },
  { key: 'is_andaman_nicobar', label: 'Andaman/Nicobar' },
];
