-- =====================================================================
-- FIX: PERMANENT APPLICATION ARCHIVE FOR TPO (FULL SCHEMA SYNCHRONIZATION)
-- =====================================================================
-- This script synchronizes the TPO Application Pool with the complete 
-- students_master schema, ensuring NO data shows as "—" when it exists.
-- Run this in your Supabase SQL Editor.
-- =====================================================================

DROP FUNCTION IF EXISTS public.get_application_pool();

CREATE OR REPLACE FUNCTION public.get_application_pool()
RETURNS TABLE (
    id UUID,
    drive_id UUID,
    student_id UUID,
    status TEXT,
    resume_url TEXT,
    interview_timestamp TIMESTAMP WITH TIME ZONE,
    company_name TEXT,
    role_offered TEXT,
    ctc_amount NUMERIC,
    first_name TEXT,
    last_name TEXT,
    reg_no TEXT,
    roll_number TEXT,
    email_address TEXT,
    mobile_number TEXT,
    department_name TEXT,
    overall_cgpa TEXT,
    current_backlogs TEXT,
    applied_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    -- Personal Metadata
    gender TEXT,
    date_of_birth TEXT,
    blood_group TEXT,
    whatsapp_number TEXT,
    alternate_email TEXT,
    aadhar_number TEXT,
    pan_number TEXT,
    passport_available TEXT,
    passport_number TEXT,
    nationality TEXT,
    state TEXT,
    district TEXT,
    mother_tongue TEXT,
    religion TEXT,
    community TEXT,
    caste TEXT,
    marital_status TEXT,
    -- Academic
    board_10th TEXT,
    school_name_10th TEXT,
    mark_10th TEXT,
    percentage_10th TEXT,
    board_12th TEXT,
    school_name_12th TEXT,
    mark_12th TEXT,
    percentage_12th TEXT,
    twelfth_reg_no TEXT,
    school_address_12th TEXT,
    diploma_studied TEXT,
    diploma_institute TEXT,
    diploma_stream TEXT,
    work_experience_years TEXT,
    current_year TEXT,
    current_semester TEXT,
    sem_1_cgpa TEXT,
    sem_2_cgpa TEXT,
    sem_3_cgpa TEXT,
    sem_4_cgpa TEXT,
    sem_5_cgpa TEXT,
    sem_6_cgpa TEXT,
    sem_7_cgpa TEXT,
    sem_8_cgpa TEXT,
    current_standing_arrear TEXT,
    history_of_arrear TEXT,
    arrears_count TEXT,
    regulations TEXT,
    batch TEXT,
    section TEXT,
    quota TEXT,
    medium TEXT,
    mode_of_education TEXT,
    mode_of_admission TEXT,
    student_status TEXT,
    -- Family
    father_name TEXT,
    father_occupation TEXT,
    father_mobile TEXT,
    mother_name TEXT,
    mother_mobile TEXT,
    is_parent_farmer TEXT,
    first_graduate TEXT,
    single_parent TEXT,
    ex_serviceman_child TEXT,
    -- Address
    door_street TEXT,
    area_village TEXT,
    pincode TEXT,
    geographic_area TEXT,
    andaman_nicobar TEXT,
    -- Professional & Other
    hostel_day_scholar TEXT,
    hostel_name TEXT,
    interested_in_placement TEXT,
    opt_out_reason TEXT,
    photo_url TEXT,
    it_skills TEXT,
    programming_languages TEXT,
    projects TEXT,
    internships TEXT,
    certifications TEXT,
    github_url TEXT,
    linkedin_url TEXT,
    leetcode_url TEXT,
    hackerrank_url TEXT,
    preferred_role TEXT,
    preferred_location TEXT,
    extracurricular TEXT,
    physically_challenged TEXT
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pa.id,
        pa.drive_id,
        pa.student_id,
        pa.status,
        pa.resume_url,
        pa.interview_timestamp,
        c.name as company_name,
        pd.role_offered,
        pd.ctc_amount,
        sm.first_name,
        sm.last_name,
        sm.reg_no,
        sm.roll_number,
        sm.email_address,
        sm.mobile_number,
        dept.name as department_name,
        sm.overall_cgpa,
        sm.current_backlogs,
        pa.created_at as applied_at,
        pa.updated_at,
        -- Profile Metadata
        sm.gender,
        sm.date_of_birth,
        sm.blood_group,
        sm.whatsapp_number,
        sm.alternate_email,
        sm.aadhar_number,
        sm.pan_number,
        sm.passport_available,
        sm.passport_number,
        sm.nationality,
        sm.state,
        sm.district,
        sm.mother_tongue,
        sm.religion,
        sm.community,
        sm.caste,
        sm.marital_status,
        -- Academic
        sm.board_10th,
        sm.school_name_10th,
        sm.mark_10th,
        sm.percentage_10th,
        sm.board_12th,
        sm.school_name_12th,
        sm.mark_12th,
        sm.percentage_12th,
        sm.twelfth_reg_no,
        sm.school_address_12th,
        sm.diploma_studied,
        sm.diploma_institute_name as diploma_institute,
        sm.diploma_stream,
        sm.work_experience as work_experience_years,
        sm.current_year,
        sm.current_semester,
        sm.sem_1_cgpa,
        sm.sem_2_cgpa,
        sm.sem_3_cgpa,
        sm.sem_4_cgpa,
        sm.sem_5_cgpa,
        sm.sem_6_cgpa,
        sm.sem_7_cgpa,
        sm.sem_8_cgpa,
        sm.current_standing_arrear,
        sm.history_of_arrear,
        sm.history_of_arrears_count as arrears_count,
        sm.regulations,
        sm.batches as batch,
        sm.section,
        sm.quota,
        sm.medium,
        sm.mode_of_education,
        sm.mode_of_admission,
        sm.student_status,
        -- Family
        sm.father_guardian_name as father_name,
        sm.occupation_father_guardian as father_occupation,
        sm.father_mobile_number as father_mobile,
        sm.mother_name,
        sm.mother_mobile_number as mother_mobile,
        sm.is_parent_farmer,
        sm.is_first_graduate as first_graduate,
        sm.is_single_parent as single_parent,
        sm.is_ex_serviceman_child as ex_serviceman_child,
        -- Address
        sm.communication_door_street as door_street,
        sm.communication_area_village as area_village,
        sm.communication_pincode as pincode,
        sm.geographic_classification as geographic_area,
        sm.is_andaman_nicobar as andaman_nicobar,
        -- Professional & Other
        sm.is_hosteller as hostel_day_scholar,
        sm.hostel_name,
        sm.interested_in_placement,
        sm.placement_opt_out_reason as opt_out_reason,
        sm.photo_url,
        sm.skills as it_skills,
        sm.programming_languages,
        sm.projects,
        sm.internship_experience as internships,
        sm.certifications,
        sm.github_url,
        sm.linkedin_url,
        sm.leetcode_url,
        sm.hackerrank_url,
        sm.preferred_job_role as preferred_role,
        sm.preferred_location,
        sm.extra_curricular as extracurricular,
        sm.is_physically_challenged as physically_challenged
    FROM 
        public.placement_applications pa
    JOIN 
        public.placement_drives pd ON pa.drive_id = pd.id
    JOIN 
        public.companies c ON pd.company_id = c.id
    JOIN 
        public.students_master sm ON pa.student_id = sm.id
    LEFT JOIN 
        public.departments dept ON sm.department_id = dept.id
    WHERE 
        pa.status IN (
            'approved_by_hod', 
            'pending_tpo', 
            'approved_by_tpo', 
            'shortlisted', 
            'interview_scheduled', 
            'selected', 
            'rejected_by_tpo', 
            'placed'
        )
    ORDER BY 
        pa.created_at DESC;
END;
$$;
